import type { CuratedEventSeed } from "./history.js";

const event = (value: CuratedEventSeed): CuratedEventSeed => value;

/**
 * High-value first-party events that normalize the recent three-month baseline.
 * These are editorially complete events, not generated filler or a news firehose.
 */
export const recentDensityEvents = [
  event({
    slug: "gemma-4-open-model-efficiency",
    title: "Gemma 4 发布：开放模型竞争继续向单位资源效率推进",
    fact: "Google DeepMind 于 2026 年 4 月 2 日发布 Gemma 4，强调在开放模型形态下提升能力与部署效率。",
    summary: "开放模型的价值正在从参数规模转向可部署性、可定制性和同等资源下的实际任务表现。",
    technical: "评估重点应从单一榜单扩展到显存占用、吞吐、量化损失、工具调用和领域微调后的稳定性。",
    industry:
      "云厂商与模型平台需要同时支持闭源前沿能力和可控开放模型，企业采购会更关注总体拥有成本。",
    future: "观察独立评测、主要推理框架支持、真实吞吐和衍生模型质量，而不是只复述官方基准。",
    business: "需要私有化或边缘部署的团队可把 Gemma 4 纳入同成本对照，但应先用真实业务集验证。",
    category: "model-release",
    company: "Google DeepMind",
    keywords: ["Gemma 4", "开放模型", "推理效率", "部署"],
    scores: [92, 52, 84, 82],
    date: "2026-04-02T16:00:49.000Z",
    source: "deepmind",
    url: "https://deepmind.google/blog/gemma-4-byte-for-byte-the-most-capable-open-models",
    tracks: ["tech-evolution", "commercialization", "to-d", "model-economics"],
    actors: ["google"],
  }),
  event({
    slug: "gemini-robotics-er-1-6-embodied-reasoning",
    title: "Gemini Robotics-ER 1.6：具身模型开始执行完整真实任务",
    fact: "Google DeepMind 于 2026 年 4 月 13 日发布 Gemini Robotics-ER 1.6，面向真实机器人任务强化具身推理。",
    summary: "机器人竞争正从单项动作演示转向包含视觉理解、任务规划、执行反馈和失败恢复的完整任务。",
    technical:
      "判断技术水平需要看跨环境泛化、动作可执行性、长任务稳定性和安全停止，语言解释是否流畅只能说明其中一部分。",
    industry:
      "具身基础模型将抬高数据、仿真、评测和硬件适配平台的价值，并加快模型厂商与机器人公司的协作。",
    future: "观察跨本体复现、真实任务完成率、人工接管次数和长时运行中的累积误差。",
    business: "机器人团队应优先建立失败分类与可回放评测，再决定是否把通用具身模型接入生产任务。",
    category: "research",
    company: "Google DeepMind",
    keywords: ["Gemini Robotics", "具身智能", "机器人", "推理"],
    scores: [93, 58, 90, 84],
    date: "2026-04-13T15:52:13.000Z",
    source: "deepmind",
    url: "https://deepmind.google/blog/gemini-robotics-er-1-6",
    tracks: ["tech-evolution", "agi-progress", "to-b"],
    actors: ["google"],
  }),
  event({
    slug: "decoupled-diloco-resilient-distributed-training",
    title: "Decoupled DiLoCo：分布式训练开始正面解决网络与节点不稳定",
    fact: "Google DeepMind 于 2026 年 4 月 22 日介绍 Decoupled DiLoCo，用解耦方式提升大规模分布式训练的韧性。",
    summary: "训练基础设施的瓶颈不只在芯片数量，也在跨节点通信、故障恢复和异构资源能否持续利用。",
    technical:
      "解耦局部优化与全局同步可以降低强同步依赖，但需要验证收敛速度、最终质量与通信节省的真实交换关系。",
    industry:
      "若方法能稳定扩展，更多跨区域和异构集群可参与大模型训练，算力调度与网络软件价值上升。",
    future: "观察更大模型复现、不同网络条件下的质量损失、故障恢复时间和单位训练成本。",
    business: "训练平台采购应把有效利用率和故障恢复纳入成本模型，而不是只比较峰值 FLOPS。",
    category: "research",
    company: "Google DeepMind",
    keywords: ["DiLoCo", "分布式训练", "训练韧性", "AI Infra"],
    scores: [91, 42, 86, 82],
    date: "2026-04-22T10:20:03.000Z",
    source: "deepmind",
    url: "https://deepmind.google/blog/decoupled-diloco",
    tracks: ["tech-evolution", "to-d", "model-economics"],
    actors: ["google"],
  }),
  event({
    slug: "ai-co-clinician-healthcare-model",
    title: "AI Co-clinician：医疗 AI 从问答助手转向协作式临床工作流",
    fact: "Google DeepMind 于 2026 年 4 月 30 日提出 AI co-clinician 方向，探索模型与临床人员协作的新工作模式。",
    summary: "医疗 AI 的产品边界正从生成建议扩展到信息汇总、假设比较、风险提示和可追溯协作。",
    technical: "系统必须处理证据来源、校准、不确定性、权限和责任链；单轮准确率不足以证明临床可用。",
    industry:
      "医疗场景会优先奖励能嵌入既有流程、保留审计并明确人工责任的系统，而不是通用聊天入口。",
    future: "观察真实临床试验、错误类型、医生采纳率、工作量变化和监管边界。",
    business: "医疗团队应从低风险信息整理切入，预先定义升级、拒答与审计要求，再扩大决策影响。",
    category: "industry",
    company: "Google DeepMind",
    keywords: ["医疗 AI", "Co-clinician", "临床工作流", "治理"],
    scores: [90, 48, 88, 86],
    date: "2026-04-30T12:14:15.000Z",
    source: "deepmind",
    url: "https://deepmind.google/blog/ai-co-clinician",
    tracks: ["commercialization", "to-b", "to-g"],
    actors: ["google"],
  }),
  event({
    slug: "gemini-3-5-frontier-action",
    title: "Gemini 3.5：前沿模型竞争进一步转向可执行行动",
    fact: "Google DeepMind 于 2026 年 5 月 15 日发布 Gemini 3.5，并以面向行动的前沿智能作为核心定位。",
    summary: "模型升级的判断标准从回答质量扩展到规划、工具使用、跨模态理解与任务完成。",
    technical:
      "可行动模型需要稳定的工具协议、状态管理、权限边界和失败恢复，峰值推理能力只是其中一层。",
    industry:
      "Google 正把模型、Workspace、Cloud 与开发者平台连接成完整分发链，竞争对象不再只是模型 API。",
    future: "观察真实任务完成率、Agent 成本、长任务失败分布和企业权限治理。",
    business:
      "企业应选择一个跨系统流程做对照实验，以完成率与人工接管率决定迁移，而非追逐发布日榜单。",
    category: "model-release",
    company: "Google DeepMind",
    keywords: ["Gemini 3.5", "Agent", "工具调用", "行动模型"],
    scores: [95, 82, 96, 94],
    date: "2026-05-15T22:50:12.000Z",
    source: "deepmind",
    url: "https://deepmind.google/blog/gemini-3-5-frontier-intelligence-with-action",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-b", "to-d"],
    actors: ["google"],
  }),
  event({
    slug: "google-antigravity-2-agent-development",
    title: "Google Antigravity 2.0：AI Coding 从补全工具走向任务级工程环境",
    fact: "Google DeepMind 于 2026 年 5 月 17 日发布 Google Antigravity 2.0，继续扩展面向 Agent 的开发体验。",
    summary: "编码工具正在围绕长期任务、仓库理解、执行反馈和多步骤交付重构，而不是只优化补全速度。",
    technical:
      "关键能力包括上下文压缩、计划可追踪、测试验证、权限隔离和长任务恢复，需要按端到端结果评测。",
    industry: "IDE、模型厂商和代码托管平台的边界继续重叠，开发者分发与工作流锁定的重要性上升。",
    future: "观察复杂仓库完成率、变更规模、回滚成本、代码审查负担和企业采用。",
    business: "研发团队应以小步集成和自动测试约束 Agent，避免用一次性大改动制造不可审查风险。",
    category: "product-release",
    company: "Google",
    keywords: ["Antigravity", "AI Coding", "Coding Agent", "IDE"],
    scores: [93, 76, 91, 92],
    date: "2026-05-17T19:43:45.000Z",
    source: "deepmind",
    url: "https://deepmind.google/blog/introducing-google-antigravity-2-0",
    tracks: ["tech-evolution", "commercialization", "to-d"],
    actors: ["google"],
  }),
  event({
    slug: "gemini-omni-native-multimodal",
    title: "Gemini Omni：原生多模态交互从能力展示走向统一产品入口",
    fact: "Google DeepMind 于 2026 年 5 月 17 日发布 Gemini Omni，强化跨文本、语音、视觉等模态的统一交互。",
    summary: "多模态竞争正在从单项理解能力转向实时组合、上下文连续性和跨模态行动。",
    technical:
      "需要同时评估时延、打断处理、模态对齐、工具调用与隐私边界，单一视觉或语音分数不足以代表体验。",
    industry: "统一多模态入口可能重塑搜索、助手、客服和创作产品，也提高设备与云端协同的重要性。",
    future: "观察实时交互延迟、跨语言表现、复杂场景稳定性和第三方应用接入。",
    business:
      "产品团队应优先选择必须同时使用两种以上模态、且结果可衡量的业务流程。单纯增加输入类型很难产生价值。",
    category: "model-release",
    company: "Google DeepMind",
    keywords: ["Gemini Omni", "多模态", "实时交互", "语音"],
    scores: [94, 80, 92, 91],
    date: "2026-05-17T19:50:57.000Z",
    source: "deepmind",
    url: "https://deepmind.google/blog/introducing-gemini-omni",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-c", "to-b"],
    actors: ["google"],
  }),
  event({
    slug: "google-io-2026-ai-platform-bundle",
    title: "Google I/O 2026：AI 从单点功能变成横跨产品与开发栈的平台层",
    fact: "Google 于 2026 年 5 月 20 日汇总 I/O 2026 的 100 项发布、演示与产品更新。",
    summary: "多项发布共同说明，模型、消费产品、Cloud 和开发工具开始共享同一套 AI 平台能力。",
    technical:
      "平台化要求统一模型接口、身份权限、上下文和观测能力，否则产品数量只会放大集成复杂度。",
    industry:
      "Google 的优势从单模型能力扩展到分发与基础设施组合，独立应用需要更明确的垂直数据与工作流壁垒。",
    future:
      "观察这些功能何时可稳定使用、能否被多个产品采用、开发者是否持续使用，以及重复能力是否逐步合并。",
    business: "采购者应按工作流选择已稳定可用的能力，避免把发布清单等同于当前生产能力。",
    category: "industry",
    company: "Google",
    keywords: ["Google I/O", "平台化", "Gemini", "开发生态"],
    scores: [92, 88, 93, 91],
    date: "2026-05-20T19:30:00.000Z",
    source: "google-ai",
    url: "https://blog.google/innovation-and-ai/technology/ai/google-io-2026-all-our-announcements",
    tracks: ["commercialization", "tech-evolution", "to-c", "to-b", "to-d"],
    actors: ["google"],
  }),
  event({
    slug: "deepmind-apac-climate-accelerator",
    title: "DeepMind 亚太加速器：前沿模型开始与区域产业问题直接绑定",
    fact: "Google DeepMind 于 2026 年 5 月 21 日宣布在亚太启动面向环境风险的加速器计划。",
    summary: "前沿实验室正通过区域合作把通用模型转成垂直问题解决能力，生态建设成为技术扩散路径。",
    technical: "项目成败取决于区域数据、领域评测、部署约束和持续运营，而不是通用模型直接迁移。",
    industry:
      "亚太市场将成为气候、农业和公共治理 AI 的重要验证场，也提供本土团队参与前沿生态的入口。",
    future: "观察入选项目、数据开放、实际部署、环境结果和项目结束后的持续性。",
    business: "相关创业团队应以可测量结果与本地数据优势参与，而不是只提供通用模型封装。",
    category: "ecosystem",
    company: "Google DeepMind",
    keywords: ["亚太", "加速器", "气候科技", "生态"],
    scores: [90, 55, 80, 82],
    date: "2026-05-21T19:46:42.000Z",
    source: "deepmind",
    url: "https://deepmind.google/blog/were-launching-the-google-deepmind-accelerator-program-in-asia-pacific-to-tackle-environmental-risks",
    tracks: ["commercialization", "investing", "to-b", "to-g"],
    actors: ["google"],
  }),
  event({
    slug: "gemma-4-12b-unified-multimodal",
    title: "Gemma 4 12B：开放多模态模型进一步压缩部署门槛",
    fact: "Google DeepMind 于 2026 年 6 月 9 日发布统一、无独立编码器的 Gemma 4 12B 多模态模型。",
    summary: "更紧凑的统一多模态架构让本地化、私有化和垂直微调获得更现实的成本空间。",
    technical:
      "无独立编码器的设计需要验证跨模态表示效率、推理吞吐、量化兼容性与不同输入长度下的稳定性。",
    industry:
      "开放模型会继续推动端侧与私有部署生态，也迫使闭源 API 用可靠性、工具链和服务证明溢价。",
    future: "观察独立多模态评测、主要硬件适配、社区微调和真实单位请求成本。",
    business: "有数据主权要求的团队可建立小规模基准，与闭源 API 按总成本和维护负担做同任务比较。",
    category: "model-release",
    company: "Google DeepMind",
    keywords: ["Gemma 4 12B", "开放模型", "多模态", "私有部署"],
    scores: [93, 70, 87, 88],
    date: "2026-06-09T14:10:19.000Z",
    source: "deepmind",
    url: "https://deepmind.google/blog/introducing-gemma-4-12b-a-unified-encoder-free-multimodal-model",
    tracks: ["tech-evolution", "commercialization", "to-d", "model-economics"],
    actors: ["google"],
  }),
  event({
    slug: "claude-fable-5-microsoft-foundry",
    title: "Claude Fable 5 进入 Microsoft Foundry：模型分发继续平台化",
    fact: "Microsoft 于 2026 年 6 月 9 日宣布 Claude Fable 5 在 Microsoft Foundry 可用，面向自主 Agent 场景。",
    summary: "企业模型采购从单一厂商 API 转向云平台内的多模型治理、身份、数据和观测统一。",
    technical: "集成价值取决于权限、网络、评测、路由和日志治理。能够调用模型只是生产部署的起点。",
    industry:
      "Anthropic 获得更广企业分发，Microsoft 则强化模型中立平台定位，多模型竞争进入云控制面。",
    future: "观察区域可用性、企业采用、路由策略、成本差异和 Foundry 内的治理深度。",
    business:
      "企业可用同一工作负载比较模型，但必须统一数据边界、回归集和失败处理，避免模型切换造成隐性风险。",
    category: "distribution",
    company: "Microsoft",
    keywords: ["Claude Fable 5", "Microsoft Foundry", "企业 AI", "多模型"],
    scores: [91, 66, 87, 90],
    date: "2026-06-09T17:00:00.000Z",
    source: "azure-ai",
    url: "https://azure.microsoft.com/en-us/blog/claude-fable-5-is-now-available-in-microsoft-foundry-powering-the-next-era-of-autonomous-agents",
    tracks: ["commercialization", "to-b", "to-d"],
    actors: ["microsoft", "anthropic"],
  }),
  event({
    slug: "openai-acquires-ona",
    title: "OpenAI 收购 Ona：Agent 竞争延伸到长期软件工程能力",
    fact: "OpenAI 于 2026 年 6 月 11 日宣布收购 Ona。",
    summary:
      "并购信号表明模型公司正在吸收关键工程团队与工作流能力，以缩短从模型到可交付 Agent 的距离。",
    technical: "整合价值取决于仓库级上下文、长任务执行、结果验证和开发者体验能否进入统一产品。",
    industry:
      "AI Coding 市场的竞争会继续从模型调用转向完整工程系统，独立工具面临平台并购与功能内置压力。",
    future: "观察团队与产品整合、能力上线、企业迁移和原有客户/开源生态的处理。",
    business: "AI Coding 创业公司需要证明独有数据、工作流或分发优势，单一功能更容易被平台吸收。",
    category: "investment",
    company: "OpenAI",
    keywords: ["OpenAI", "Ona", "收购", "AI Coding"],
    scores: [94, 78, 91, 90],
    date: "2026-06-11T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/openai-to-acquire-ona",
    tracks: ["investing", "commercialization", "to-d"],
    actors: ["openai"],
  }),
  event({
    slug: "deployment-simulation-model-behavior",
    title: "部署前行为模拟：模型安全评测开始贴近真实使用环境",
    fact: "OpenAI 于 2026 年 6 月 16 日发布通过模拟部署预测模型行为的研究。",
    summary:
      "静态 benchmark 难以覆盖真实用户、工具和组织规则带来的行为变化，评测开始向场景化部署模拟演进。",
    technical:
      "模拟方法必须处理环境代表性、对抗行为、长程反馈和评价器偏差，并证明能预测真实部署失败。",
    industry: "模型发布与企业采购都需要更接近实际工作流的预发布验证，评测平台和红队能力价值上升。",
    future: "观察模拟结果与真实事故的相关性、外部复现、覆盖范围和对发布决策的实际影响。",
    business: "高风险应用应建立影子部署和场景模拟，并在上线检查中明确失败类型和停止条件。",
    category: "research",
    company: "OpenAI",
    keywords: ["部署模拟", "模型行为", "安全评测", "红队"],
    scores: [92, 54, 89, 88],
    date: "2026-06-16T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/deployment-simulation",
    tracks: ["agi-progress", "tech-evolution", "to-b", "to-g"],
    actors: ["openai"],
  }),
  event({
    slug: "gemini-3-5-flash-computer-use",
    title: "Gemini 3.5 Flash Computer Use：浏览器 Agent 进入低延迟模型层",
    fact: "Google DeepMind 于 2026 年 6 月 24 日发布 Gemini 3.5 Flash 的 computer use 能力。",
    summary:
      "浏览器操作从外部脚本编排逐步成为模型原生能力，但可靠性、安全和成本仍决定能否生产使用。",
    technical:
      "需要按页面理解、动作定位、状态验证、异常恢复与提示注入防护分层评测，不能只看成功 demo。",
    industry:
      "Computer use 会压缩通用 RPA 与简单浏览器 Agent 的差异，价值向治理、垂直流程和可靠执行迁移。",
    future: "观察真实网站成功率、长任务成本、提示注入事故、权限控制和企业审计能力。",
    business: "团队应先选择可回滚、低权限流程做影子运行，并以完成率和人工接管率决定扩大范围。",
    category: "product-release",
    company: "Google DeepMind",
    keywords: ["Computer Use", "Browser Agent", "Gemini 3.5 Flash", "自动化"],
    scores: [94, 76, 93, 92],
    date: "2026-06-24T16:30:01.000Z",
    source: "deepmind",
    url: "https://deepmind.google/blog/introducing-computer-use-in-gemini-3-5-flash",
    tracks: ["tech-evolution", "commercialization", "to-b", "to-d"],
    actors: ["google"],
  }),
] as const satisfies readonly CuratedEventSeed[];
